.babelrc
package.json
spec/runner.js
spec/support/jasmine.json
src/calendar/header/index.js
src/calendar/index.js
src/index.js
src/interface.js

This PR brings full web compatibility to address issue #2
Changes made:
Remove mixed import/module.exports for Webpack 2 support
Allow `<CalendarHeader />` component to take `leftArrow` and `rightArrow` props allowing any component to be used for arrow replacement.

feature(calendar): support custom arrow components

---

src/agenda/index.js

Callback property when the day changes via scroll event.
Currently the only way to know when days change is via `onDayPress`. However, if the day is changed via scroll events, that information is tucked away. This exposes that change via `onDayChange`.
```jsx
<Agenda
...
onDayChange={day => this.doSomethingWithNewDay(day)}
/>
```
My only gripe is that there's now two date change callbacks, but it is helpful to know the distinction, so it's not a huge complaint.
Although it might be worth consolidating both behind a "day changed" property, and perhaps passing a second argument describing the event source (`'press'` vs `'scroll'`)

feat(agenda): add onDayChange prop

---

src/calendar/day/basic/style.js
src/calendar/day/interactive/style.js
src/calendar/header/style.js
src/style.js

This pull request gives the ability to set appStyle props to change the fontFamily and fontSize for <Calendar> component. 
The default "System" font and default sizes are retained and used as a backup if the props are not defined.
There likely is a more elegant way to do this and if you have any suggestions I'd be happy to make modifications.
**New props**
- textDayFontFamily
- textMonthFontFamily
- textDayHeaderFontFamily
- textTodayFontFamily
- textDayFontSize
- textMonthFontSize
- textDayHeaderFontSize
**Original**
**With props added**

Updates to <Calendar> styles to allow customization

---

src/agenda/index.js

#101 reproduces differently on my machine when weekday names are too long, so this may not be a full fix.

Prevent week day names from using more than one line. Related to #101

---

src/agenda/index.js

As far as I can tell, when onLayout for root View is called, layout for its children is not always complete. The problem got fixed by waiting until layout is finished for scrollPad and only then changing scroll position for it.

#97 Fix calendar height problem after Agenda height is changed

---

README.md

This made me loose some time due to not understanding why `calendarBackground` was not applying to the reservation-list

Add missing "backgroundColor" theme prop

---

README.md
src/agenda/index.js

current markedDates=items default setting is not flexible enough for my usecase which if to mark the date only if one row of the day match a predicate

Agenda: allow custom markedDates

---

.gitignore
src/calendar-list/index.js

Hey hey! Thanks again for such an amazing library! Really love the API and its such a pleasure to work with! We are using this library for our cross-platform component lib and on web the calendar list view does not load months once the scroll into view due to the onScroll handler returning early for any platform that is not `android`. In a `react-native-web`/universal component system this causes web to not work.
____
____
I have updated the check to only return specifically for ios and this fixes the issue. Let me know if you need me to do anything else! Thanks again for all of the hard work!
___
___

fix(calendar-list): fixes onscroll returning early on web

---

src/calendar-list/index.js

Loading `CalendarList` without `current` prop set would cause it to be incorrectly scrolled to the earliest possible date.
The `CalendarList` should be scrolled to a current date in case no `current` prop is specified.
Use `this.state.openDate` instead of `this.props.current` to properly handle the case where the `current` prop is not set and is instead defaulted to new Date.

Fix CalendarList initialScrollIndex

---

src/calendar/day/interactive/index.js

This pull request fixes #61 and #158 and is a fix across iOS (although not problematic) and Android.
**Fix**
The fix simply applies a `backgroundColor` style to the filler.
**Screenshot**
Before:
After:

Fixing marked dates gap issue on Android

---

README.md
src/agenda/index.js

We had a need to render content based off whether the calendar was opened or not.  This just adds a prop to have a callback function fire with the state of the calendar when it's toggled opened or closed.  Would love to get this merged asap because it's so small!  Thanks.

Agenda View toggled opened/closed callback

---

README.md
src/calendar-list/index.js

Just a tiny PR to add a `showScrollIndicator` prop to Calendar List that sets `showsVerticalScrollIndicator` on the rendered `FlatList`.
Now that I'm writing this, I'm wondering whether I should keep the prop names the same so it's essentially exposing `showsVerticalScrollIndicator`?

Calendar List allow showing vertical scroll indicator

---

src/calendar/day/basic/index.js

This PR addresses #149 with a potential solution. Thought I'd kick off the PR to discuss possible solutions.
I think a few users feel touch events should be disabled by default for dates which are marked "disabled". I agree that this is the best solution but I'm open to other suggestions such as an additional prop to toggle this behaviour.

Disabled touch events for dates marked "disabled"

---

README.md
example/src/screens/calendars.js
src/calendar/index.js

Fixes the aligmet issue: https://github.com/wix/react-native-calendars/pull/239#issuecomment-349905968
- Adds prop types for showWeekNumber
- Documents showWeekNumber
- Changes to using the `<Day />` component for week numbers
- Shows correct number for week number 53 (due to leap years)
I will do another PR that adds a prop to override the styles, component and onPress for the week number 👍

🎉 Improve week numbers

---

src/calendar/day/period/index.js

Faced this issue while resetting `markedDates` to empty object. The selected dates disappeared, because `textColor` was still set to white (background was also white). Also `getDrawingStyle ` should not use `this.props.marking`, since it's getting the marking data from the parameter.

getDrawingStyle: use marking data from given parameter instead of from current props

---

README.md
src/calendar/day/multi-dot/index.js

Referring to the discussion in #212, I made the key property in multi-dot markers optional. If key is omitted then the array index is used as key instead. README.md has been updated accordingly.

Made key property in multi-dot markers optional

---

src/calendar/day/multi-dot/index.js

To make the key fully optional, we should skip the check of the existence of key prop as well.
connect #342
ref https://github.com/wix/react-native-calendars/pull/324/files#diff-7dbb7000318300fafc323390f0d46412L65

Fix optional multi dot's key 

---

src/calendar/style.js

The calendar fills the view with white space because of the `flex: 1`. Styling of surrounding things should not be part of the library. It's much easier to add it
```jsx
<View style={{flex: 1}} backgroundColor=...>
<Calendar theme={{calendarBackground: 'transparent'}} />
</View>
```
than removing it using this library.

remove flex: 1 from calendar container style

---

src/calendar/index.js

This PR fixes a bug where the week numbers on the `Calendar` component would be selectable, and would cause the application to crash, as described on #367
Passed the marking prop `{disableTouchEvent: true}` to the `Day` object returned by the `renderWeekNumber` method on the `Calendar` component.

Fix selectable week numbers

---

src/calendar/header/index.js

There was a bug where the months were moving backwards when I clicked the right arrow. It was a simple mistake of calling subtractMonth instead of addMonth.

[bug-fix] fix subtract month onPressRight bug

---

README.md
example/src/screens/calendars.js
src/calendar/day/multi-dot/index.js

```selectedColor``` in the multi-dot section inside README.md is not working and not logically correct because code cannot decide which dot ```selectedColor``` property would be applied if we have multiple dots on one day.
This PR moved ```selectedColor``` one level up (look README.md commit) and adds missing functionality.
I'm using it in my project. It would be cool if you merge this.

Make multi-dot strategy to respect provided selectedColor

---

src/calendar/day/basic/style.js

On iOS the number inside the date circle is not vertically aligned but is on Android.
This PR sets the margin top of the date to be by platform type

[Style] Sets date margin by platform type

---

src/calendar/index.js
src/calendar/style.js

The problem was that if we change the day width (in our example the width was being calculated according to the screen dimensions), hidden extra days stayed 32 and that caused misplace of days in rows that included hidden extra days.
Related to #307

Move hardcoded width of hidden extra days to style

---

src/agenda/index.js
src/calendar-list/index.js

Added removeClippedSubviews={} to CalendarList and Agenda.
Fix an issue with tab navigator of react-navigation passing removeClippedSubviews={false} to Agenda

add remove clipped subviews option

---

src/calendar-list/index.js

remove duplicate this.getItemLayout 
in file src/calendar-list/index.js  we have two this.getItemLayout declaration in L80 and L83

😈 fix(remove duplicate): remove duplicate this.getItemLayout 

---

src/calendar-list/index.js

It seems the list size here should be the sum of this.pastScrollRange and this.futureScrollRange rather than product.

😈 Fix initialListSize calculate error

---

src/calendar-list/index.js

Seems the state `initialized ` has never been used. Shall we remove it for less confusion?

😈 Fix remove unused state

---

src/calendar-list/item.js

Keep the same default to `true`, but allow to show them when `<CalendarList hideArrows={false} />`

Allow to show arrows in CalendarList

---

src/calendar/day/basic/index.js
src/calendar/day/basic/style.js
src/calendar/day/custom/index.js
src/calendar/day/custom/style.js
src/calendar/day/multi-dot/index.js
src/calendar/day/multi-dot/style.js
src/calendar/day/multi-period/index.js
src/calendar/day/multi-period/style.js
src/calendar/day/period/index.js
src/calendar/day/period/style.js
src/style.js

This PR gives more flexibility to style today container. It adds a new todayBackgroundColor:
```jsx
<CalendarList
theme={{
todayBackgroundColor: 'blue',
}}
/>
```
but also allows more customisations:
```jsx
<CalendarList
theme={{
'stylesheet.day.basic': {
today: {
backgroundColor: 'blue',
borderRadius: 5,
}
}
}}
/>
```

Add todayBackgroundColor in day components

---

src/agenda/index.js

The calendar list rendered by the agenda has the initial width as the default prop,
on orientation change, a wrong width is used to render the calendar list, the fix
explicitly adds the calendarWidth prop based on agenda's `this.viewWidth`
Examples of wrong renders that are solved with this:

Fix agenda wrong render when orientation changes.

---

example/android/app/build.gradle

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Remove Gradle warning

---

src/agenda/index.js

weekDaysNames have an array of days in abbreviated letters, e.g. "S" for Sunday, and "S" for Saturday. React Native does not like that the key element have duplicates of the same key. This causes the "Encountered two children with the same key" warning. 
No warnings appear in AgendaView.
What actually happened when you performed the above actions?
If there's an error message, please paste the *full terminal output and error message* in this code block:
```
Encountered two children with the same key, `T`...
Encountered two children with the same key, `S`...
```
Added the index of the weekDaysNames array avoids duplicates, removing the warning.

Avoid Duplicate Key warnings in AgendaView 

---

src/calendar-list/index.js

You had a mistake on CalendarList's props 'scrollEnabled'.

[Fix Bug] 'scrollEnabled' props doesn't work

---

src/calendar-list/index.js
src/calendar-list/item.js

this.props.style to be passed to the list item (that holds the Calendar), while the FlatList will be passed this.props.containerStyle instead. Thus separating the style passed to the CalendarListItem from the styles passed to the FlatList.

Allow passing style to calendarListItem

---

README.md
example/src/screens/calendars.js
src/agenda/reservation-list/index.js
src/calendar/header/index.js
src/style.js

The indicator color was not editable.
The default color of React Native ActivityIndicator is gray:
https://facebook.github.io/react-native/docs/activityindicator#color
- added indicatorColor to the default theme styles
- added color prop for both ActivityIndicator renderings
- included indicatorColor in README and example

Add theme color for indicator

---

src/calendar-list/index.js
src/calendar-list/item.js
src/calendar/header/index.js

Replaces #631 
Before fix:
After fix:
These gifs can be explained by [this comment:](https://github.com/wix/react-native-calendars/pull/631#discussion_r279191482)
> Also, If I remember correctly, this is **needed** for navigating months in `CalendarList`.
> 
> This is because `CalendarList` renders a list of `CalendarListItem` which renders a `Calendar` which includes a `CalendarHeader`, when the left/right navigation arrows of the `CalendarHeader` are pressed, instead of navigating along the `CalendarList`, the `Calendar` is updated in place to show the month navigated to.
> 
> So for example, if `CalendarList` looked like:
> 
> ```
> -------+-------+-------+-------+
>  Index |   0   |   1   |   2   |
> -------+-------|-------|-------|
>  Month |  Jan  |  Feb  |  Mar  |
> …
```

Fix: Navigation arrows not navigating along 'CalendarList'

---

src/expandableCalendar/index.js

Just missed a return statement which made the `renderArrow` override useless on the exandableCalendar

Fix ExpandableCalendar arrow override not working

---

src/expandableCalendar/agendaList.js

I would like to disable stickySectionHeadersEnabled but I can't do it.
I've looked into the code and found that It hard code stickySectionHeadersEnabled props. So, I think we should delete it and define the default value instead.

Support override stickySectionHeadersEnabled

---

src/calendar/index.js

I can understand why this PR might not get accepted but I needed a reference to the header for a project. Reason being we had custom arrows placed to the side of the calendar so I wanted to programmatically call the onPressLeft/onPressRight functions on the header i.e. `this.calendar.header.onPressLeft()`

Added ref to CalendarHeader

---

src/agenda/index.js

The line 335 use the exactly Math.max calculation of the method initialScrollPadPosition()

DRY in agenaHeight, reuse initialScrollPadPosition

---

src/calendar/updater.js

This fix is needed to update the Calendar when only the `displayLoadingIndicator` has changed.

Fix displayLoadingIndicator when no others props changes.

---

README.md
src/calendar/index.js

`left`-> `right`
This is the right expression.
The eating hand is in the right direction, and the other hand is in the left direction.
**JUST JOKE**😉

Modify typo in README.md

---

src/agenda/index.js

Fix for "Scroll Throttle too slow for Agenda scrolling"  [#441](https://github.com/wix/react-native-calendars/issues/441)

UPD Agenda scrollEventThrottle from 1 to 16

---

src/calendar/header/index.js

Problem:
If you have a custom logic to render the arrows on the calendar header, those changes won't trigger a re-render on the calendar header component due to some restrictions on the `shouldComponentUpdate` of the Header component.
Use case:
```js
const canNavigateForward = useMemo(() => ...logic, [deps])
const canNavigateForward = useMemo(() => ...logic, [deps])
const onRenderArrow = useCallback(
direction => (
<MyCustomArrow
direction={direction}
enabled={direction === 'left' ? canNavigateBackward : canNavigateForward}
/>
),
[canNavigateForward, canNavigateBackward]
)
return (
<CalendarList
{...baseProps}
renderArrow={onRenderArrow}
/>
)
```
Solution:
Check if the function has changed from the previous props and it all works.

Re-render the header when the renderArrow function changes

---

src/calendar-list/index.js

Most of the other props used by `FlatList` delegate to `CalendarList`'s props anyway so it makes sense that `keyExtractor` should be accessible this way too. In our use case we need to refresh the calendar because of dynamically loaded data so being able to control the keys is useful.

Adds a `keyExtractor` prop to CalendarList

---

README.md

If you wan't to whitelist specific dates you can use the "disabledByDefault" prop to disable all dates and then explicitly add disabled: false to the dates that should be enabled. I found this to be very useful.
<Calendar
markedDates={{  'YYYY-MM-DD': { disabled: false }}
disableByDefault={false}
/>

Add disabledByDefault props to docs

---

src/agenda/index.js

The error is:
TypeError: undefined is not an object (evaluating 'this.scrollPad._component.scrollTo') AgendaView#setScrollPadPosition index.js:129:27
By removing "_component" and leaving this.scrollPad.scrollTo seems to fix it

Fix React Native v0.62 issue

---

src/expandableCalendar/index.js

See my comment here: https://github.com/wix/react-native-calendars/issues/874#issuecomment-576696278
Whether it is the right fix, I don't know. But due to an (unexpected?) order in panResponder callbacks the height will be set to NaN, causing native issues.
if 'panResponderEnd' gets called before 'handlePanResponderMove', `this._height` will be set to `undefined`, which will lead to NaN's coming out of Math.[min|max] calls.

Fix undefined height in expandableCalendar

---

src/calendar/header/index.js
src/calendar/index.js

So I found out that **HeaderCalendar** Component is using `testID` from `this.props`
But... PropTypes didn't ask for a `testID` and **Calendar** Component didn't pass `testID` to **HeaderCalendar** Component.
So I made this PR to fix that.
Related PR: #865 #882

[FIX] Adding test id in Calendar Component

---

example/src/screens/calendars.js
src/calendar/day/basic/index.js
src/calendar/day/period/index.js
src/calendar/dot/index.js
src/calendar/dot/style.js
src/calendar/header/index.js
src/calendar/header/style.js
src/calendar/index.js
src/style.js

Adding the option to customize style for dates.
You can pass `disabledDaysIndexes` array and customize the color with `textSectionTitleDisabledColor` using theme prop.
Please refer to:
https://github.com/wix/react-native-calendars/issues/1153

Customize disable days

---

src/agenda/index.js
src/calendar/index.js

When running build on a docz site, I came across this error....
```
Module not found: Can't resolve 'react-native-web/dist/exports/ViewPropTypes'
```
(full stack trace below)
viewPropTypes was removed in a recent version of React Native (0.6 maybe). After some investigation, it appears RN Calendars has some logic to fallback if the viewPropTypes isn't exported, but it seams that logic was not correct.
This PR ensures that RN Calendars correctly handles the case where viewPropTypes is not exported.
Full stack trace of error
```
✖  fatal     Error: ./node_modules/react-native-calendars/src/agenda/index.js 
Module not found: Can't resolve 'react-native-web/dist/exports/ViewPropTypes' in '/XXXXXX/node_modules/react-native-calendars/src/agenda' …
```

fix: Correctly handle case where viewPropTypes is not exported from RN

---

src/calendar/day/period/index.js

implemented custom container and text style on Calendar, markingType: period.
Is now possible to customize text and container style of each day of Calendar markingType={'period'} by adding to a day in markedDates customTextStyle={} and/or customContainerStyle={}.

implemented custom style on Calendar type: period

---

src/agenda/index.js
src/calendar/index.js

Hey, this is the first time making a pull request on an open-source project so please tell me if I did something wrong.
With my team, we're developing our component library using storybook and react-native, and we're using this calendar. unfortunately, I kept getting `Cannot read "style" of undefined`. After some digging, I found out that `ViewPropTypes` doesn't exist anymore in `react-native-web` since version `0.12.0` (current version: `0.13.3`), so I made this pull request in order to fix that.
I tested that it works on both mobile and web.

fix for react-native-web > 12.0

---

src/calendar-list/index.js

This PR fixes error on #915.
I think the default value of removeClippedSubviews are reversed.
`src/calendar-list/index.js`
```diff
-   removeClippedSubviews: Platform.OS === 'android' ? false : true,
+   removeClippedSubviews: Platform.OS === 'android' ? true : false,
```
Because default value of removeClippedSubviews are true for Android and false for iOS on react-native.
[react-native/Libraries/Lists/FlatList.js](https://github.com/facebook/react-native/blob/3c9e5f1470c91ff8a161d8e248cf0a73318b1f40/Libraries/Lists/FlatList.js#L160-L170)
```
const defaultProps = {
...VirtualizedList.defaultProps,
numColumns: 1,
/**
* Enabling this prop on Android greatly improves scrolling performance with no known issues.
* The alternative is that scrolling on Android is unusably bad. Enabling it on iOS …
```

fixed #915

---

src/calendar/updater.js

Fix changing `disableArrowLeft`, `disableArrowRight` doesn't update calendar header
adresses #1284

Fix: disableArrowLeft, disableArrowRight update

---

src/calendar-list/item.js

Hello,
In case not forwarding the `disabledDaysIndexes` prop from `CalendarListItem` to `Calendar` wasn't intentional, here is the missing prop.
If it is intentional - eg. for use-cases where the indexes depend on the "page" in the FlatList - can I help getting something done to have this feature with `CalendarList` ?
Many thanks !

Forwarding missing disabledDaysIndexes from CalendarListItem to Calendar

---

src/agenda/reservation-list/index.js
src/agenda/reservation-list/reservation.js

This PR fixes the following things
1. The Agenda's **renderEmptyData**, when provided, is called but not renders anything
2. The Agenda's reservation component, is missing the **theme** propType and some theme overrides are not working

Fix Agenda's "renderEmptyData" not rendering and missing theme propType

---

src/calendar/day/period/index.js

This would fix a common problem with starting and ending date in period selection not being rounded.

Fixed startingDate and endingDate style

---

example/src/app.js
src/expandableCalendar/weekCalendar.js

On Android RTL there's a known issue with Scroll components returning wrong offset values. 
The value is actually reversed, which cause lots of miscalculations. 
The fix reverse the offset value back. 
Another issue I noticed (that is probably related to the whole RTL mess) is that on Android RTL there's an initial unexpected scroll event. 
I disabled this unwanted event to avoid weird issues on mounting

Fix issue with reversed scroll offset values on Android RTL

---

CHANGELOG.md
src/calendar-list/index.js
src/calendar/header/index.js
src/expandableCalendar/index.js

ExpandableCalendar - fix static header updates when pressing header arrows by calling addMonth() from onPressArrowLeft/Right callback

ExpandableCalendar - fix static header updates

---

src/agenda/index.js
src/calendar/index.js

`ViewPropTypes` are deprecated in `react-native` ( https://github.com/react-native-community/discussions-and-proposals/issues/29 , https://github.com/react-native-community/discussions-and-proposals/issues/29 ) and were already removed from `react-native-web`.
Supposedly #1236 should fix building with `react-native-web` 12+, however that did not work for me and many others (see #1033). I'm still getting the error `"Attempted import error: 'ViewPropTypes' is not exported from 'react-native' (imported as 'ReactNative')."` 
It seems to me that the usage of `ViewPropTypes` does not add a lot of value anyways, the generic types like `PropTypes.object` from the `prop-types` package are used for most type definitions in `Calendar` and `Agenda`.
Therefore, i propose removing the reliance on …

remove usage of ViewPropTypes

---

src/calendar-list/index.js
src/calendar-list/style.js

In reference to this https://github.com/wix/react-native-calendars/pull/1313
Original description:
> This fixes CalendarList / Agenda rendering when running on web via Expo.
> 
> Thanks to @bkniffler with his fix for touch support on web here: [bkniffler@7a0f986](https://github.com/bkniffler/react-native-calendars/commit/7a0f986bbef1f84b0fd6901af6974c8bcd7436c2)
> 
> The main issue was that `FlatList` scrolling only works on web if the parent component has a `flex` style. Source: [necolas/react-native-web#1436 (comment)](https://github.com/necolas/react-native-web/issues/1436#issuecomment-612845122)
> 
> Also incorporated fixes for some `PropTypes` errors on web, thanks @nandorojo: [#1033 (comment)](https://github.com/wix/react-native-calendars/issues/1033#issuecomment-712977254)
> 
> …

fix 'calendar-list' not rendering on web

---

src/calendar-list/index.js

Fixed missing horizontal prop in CalenderList, otherwise "horizontal" is always undefined in CalendarListItem and therefore the standard onPressArrow... functions are never called.
This should fix the following issue: #1438

Fixed undefined horizontal prop in CalendarListItem

---

src/expandableCalendar/index.js

Add openThreshold and closeThreshold props to allow the user to control the pan gesture threshold.
Set the default threshold to 30px after discussion with the UX. 
Relevant issue: https://github.com/wix/react-native-calendars/issues/1442

Feat/Add openThreshold and closeThreshold props

---

package.json
src/dateutils.js
src/expandableCalendar/week.js
src/expandableCalendar/weekCalendar.js

Few props triggered wasteful render in the Week component that being rendered in the WeekCalendar component. 
- style 
- context
- markedOptions
I fixed `style` by memoizing its value, this is almost never change so the memoization here make sense. 
For `context`, I used `extractComponentProps` util to avoid passing irrelevant props to Week component
And last, most complicated one, `markedDates` I noticed that it changes usually only for the present/current week. 
So what I did is pass the "fixed" markedDates only for the current week. 
This fix prevents rendering of all weeks when changing selected date in the current week

Reduce wasteful renders by memoizing props passed to week component

---

src/expandableCalendar/index.js

In my previous PR, in WeekCalendar, I added an optimization to when I pass on markedDates to avoid unnecessary render. 
In ExpandableCalendar we call `this.getMarkedDates` and pass the result to WeekCalendar and then in WeekCalendar we call it again only if this is the current week. 
But because ExpandableCalendar go thru `this.getMarkedDates` anyway, this optimization is lost. 
Anyway, see the small fix I did, it should fix this issue

Fix the markedDates we pass to WeekCalendar

---

src/dateutils.js
src/expandableCalendar/calendarProvider.js
src/expandableCalendar/weekCalendar.js

In WeekCalendar component, the `componentDidUpdate` trigger a state change when it's not necessary. 
In the case I change between days on the same week by pressing, there's no need to update the items of the week

avoid updating WeekCalendar when stayin on the same week

---

CHANGELOG.md
example/src/screens/calendars.js
example/src/screens/expandableCalendar.js
example/src/screens/horizontalCalendarList.js
src/agenda/index.js
src/agenda/reservation-list/index.js
src/agenda/reservation-list/reservation.js
src/calendar-list/index.js
src/calendar-list/item.js
src/calendar/day/basic/index.js
src/calendar/day/index.js
src/calendar/day/period/index.js
src/calendar/header/index.js
src/calendar/index.js
src/dateutils.js
src/day-state-manager.js
src/expandableCalendar/agendaList.js
src/expandableCalendar/calendarProvider.js
src/expandableCalendar/index.js
src/expandableCalendar/week.js
src/expandableCalendar/weekCalendar.js
src/interface.js
src/interface.spec.js

The idea of this PR is to reduce renders by memoizing render calls and object creation and reducing new object creation to avoid new refs.
I also added functionality to the demo screens, move toString() calls to `toMarkingFormat` in the `interface` file, and is today checks to `isToday` in `dateutils` file.
Small bugs fix in Period and Basic days 'marking'.
ExpandableCalendar and WeekCalendar - changing the way the selected date is marked. Instead of using 'markedDates' now using 'state' and 'context'.

Memoize and prop objects

---

CHANGELOG.md
example/src/screens/expandableCalendar.js
src/expandableCalendar/agendaList.js

1) Omit 'context' from props passed to SectionList.
2) Remove arrow function from `onScrollToIndexFailed`.
3) Demo - replace Alerts with console.

AgendaList - omit 'context' from props passed to SectionList

---

scripts/release.js

Fix release script. 
Apparently boolean env vars in jenkins are strings and not boolean. 
So both `'false'` and `'true'` are truthy

Fix relesae script

---

src/timeline/Packer.js

I've met a problem where my events did not appear on the timeline calendar. I've dug into the code and found the `buildEvent` function which calculates event height and top in the wrong way and always returns negative values.

Fix timeline event height and top calculations

---

README.md
example/src/screens/agenda.js
src/agenda/index.js

This PR resolves issues #457 #305 #937
Adds:
1. The calendar can be closed by dragging the knob upwards.
2. When the user single taps the knob, the calendar will either open or close based on the current state.
3. Exposes `setCalendarOpen` function that can be used to open/close calendar programmatically e.g. `refAgenda.current.setCalendarOpen(false)`

Use knob to close the Agenda' s calendar view

---

.npmignore
package.json
src/calendar/day/basic/index.tsx
src/calendar/day/basic/style.ts
tsconfig.json

Since the current published version of calendars include ts files it causes issues for dependent modules' tests. 
In order to fix it, I updated the build process (it similar now to what we have in uilib)
- I added a `build:ts` command for building typescript 
- The build generates `js/jsx` files out `ts/tsx` files and also add appropriate `d.ts` files (for files that were migrated)
- In `.npmignore` I ignore `ts/tsx` files so they won't be included in the published version of calendars lib
- In our Jenkins configuration I added the `build:ts` step - meaning that from now on if there are TS build issues the build will fail (which is good)

Fix build process of TS

---

src/expandableCalendar/index.js

Resolve https://github.com/wix/react-native-calendars/issues/1488.
This is a release blocking issue for us sadly, so any feedback would be hugely appreciated.
As prop drilling is not happening for `onPressArrowLeft` and `onPressArrowRight` in  the `ExpandableCalendar` component, it should be included in the custom function which are being passed.
As a result, it is not possible to use these props in the `ExpandableCalendar` component. They just aren't called.

Fix: Arrow press callbacks on expandable calendar

---

src/dateutils.js
src/day-state-manager.js

Don't mix import and module.exports in the same file:
[https://github.com/webpack/webpack/issues/4039#issuecomment-419284940](https://github.com/webpack/webpack/issues/4039#issuecomment-419284940)
PR to resolve this error: `Cannot assign to read only property 'exports' of object '#<Object>'`

change import to require - Cannot assign to read only property 'exports' of object '#<Object>'

---

src/calendar-list/index.tsx
src/calendar-list/item.tsx

Got back `prop-types` since it's in use for mapping for performance reasons.

js types - for mapping

---

src/expandableCalendar/index.js

fixes #1102 #1370
`onDayPress` is currently overriden so it is never called.
This fix calls `this.props.onDayPress` if present.

ExpandableCalendar fix onDayPress not working

---

src/expandableCalendar/agendaList.js

Allow `onScrollToIndexFailed` to be passed via props.
We are facing the same issue as mentioned in https://github.com/wix/react-native-calendars/issues/962. This issue can be fixed by calling `scrollToIndex` (to the failed scroll index) inside the `onScrollToIndexFailed` method. Currently, there is no way to override this prop.

agendaList - remove onScrollToIndexFailed

---

README.md

@lidord-wix you may want to review since you [removed](https://github.com/wix/react-native-calendars/commit/785b07da836a93bd4d2183a82cb47153d0c8bd08#diff-14f587f4d3b549c25438c22da7463bb3b7862c24b008fe7cb5d816a5d34536d9) the `STYLESHEET_ID` const that was referenced previously

Fix README links for typescript

---

src/calendar-list/item.tsx

The marking of the last line in a calendar list item with 6 lines of dates is cut.

fix CalendarListItem height

---

example/src/screens/expandableCalendar.tsx
src/agenda/index.tsx
src/agenda/reservation-list/index.tsx
src/agenda/reservation-list/reservation.tsx
src/calendar-list/index.tsx
src/calendar/day/basic/index.tsx
src/calendar/day/index.tsx
src/calendar/day/marking/index.tsx
src/calendar/day/period/index.tsx
src/calendar/header/index.tsx
src/calendar/index.tsx
src/component-updater.js
src/expandableCalendar/Context/Presenter.ts
src/expandableCalendar/WeekCalendar/presenter.ts
src/expandableCalendar/agendaList.tsx
src/expandableCalendar/index.tsx
src/timeline/Timeline.tsx

webpack can not remove unuse methods in lodash, because we use `require('lodash')` to import it
so change to `require('lodash/methodX')`

change lodash import way to make more tree-shakeable

---

src/expandableCalendar/index.tsx

Fix two bugs with ExpandableCalendar's today button:
1. Pressing on today button takes to the wrong date - production bug - WOAUILIB-2106
2. Pressing on today button while the visible month is the same month in a different year (09/2022 for example) takes to the right date but to the wrong month (the visible one).

ExpandableCalendar's today button bugs

---

.eslintrc.js
example/src/screens/menu.js
src/calendar/index.spec.js
src/componentUpdater.spec.js
src/dateutils.spec.js
src/expandableCalendar/Context/Presenter.spec.js
src/expandableCalendar/WeekCalendar/presenter.spec.js
src/interface.spec.js

- Fix eslint configuration to use `typescript-eslint/recommended` - this fix the issue where eslint consider typings as unused vars
- Fix all new errors resulted from adding the new `typescript-eslint/recommended` plugin

Fix eslint config and fix lint errors

---

src/expandableCalendar/asCalendarConsumer.tsx

The conversion of `ExpandableCalendar` to TypeScript in #1598 introduced a breaking change to the behavior of `contentRef` in `CalendarConsumer`. Before, `contentRef` held a reference to the wrapped component. Now, `contentRef` is always `undefined`. This PR returns to the previous behavior.
Fixes #1634

Fix contentRef in CalendarConsumer

---

src/agenda/style.ts

Fixed typo in styles which means an animated view doesn't get `flex: 1` as it should.

Fix: Agenda style Typo (animatedContiner -> animatedContainer)

---

CHANGELOG.md
README.md
src/calendar/index.tsx
src/expandableCalendar/Context/Presenter.ts
src/expandableCalendar/Context/Provider.tsx

Context Provider - fix onDateChange return value.
The fix is of the return value from ContextProvider's 'onDateChanged' callback (string instead of Date), which resulted in a type fix for several related methods.

Context Provider - fix onDateChange return value

---

src/expandableCalendar/index.tsx

Currently, if `ExpandableCalendar` is open, it will always close when a day is pressed, and there is no way to override this behavior. This PR adds a new prop `closeOnDayPress` to `ExpandableCalendar`, which when `false` will not close an open calendar when a day is pressed. This property defaults to `true` to maintain backward compatibility.

Add closeOnDayPress prop to ExpandableCalendar

---

README.md

The original one didn't include installing pods & entering the cloned repo

Add missing steps to 'try it out' section of readme

---

src/calendar/day/index.tsx

Lodash get can't resolve XDate.locales[XDate.defaultLocale] because it can't retrieve the value of XDate.defaultLocale since it's used as a string and not as a value in the path parameter of the _.get method. .
This PR implements a fix to get the values natively with JS instead of using lodash. 
It also fixes the case that when the prop `formatAccessibilityLabel` is not defined, the hardcoded string 'today' is used instead of using the XDate translated value.

fix: day accessibility label localization

---

src/agenda/reservation-list/reservation.tsx

The doc states :
`// Specify how each date should be rendered. day can be undefined if the item is not first in that day`
However, the tag 1.1269.0  has broken the behaviour and `Agenda.renderDate` is called only for the first item of the day now.

Agenda renders only for the first item of the day

---

.buildkite/pipeline.yml
scripts/release.js

@Inbal-Tish 
I changed the script and the pipeline so we'll have `snapshot` version for each master build, exactly like we have in public uilib. 
Please take a look.

Change release process to publish snapshot versions for master commits

---

src/agenda/reservation-list/index.tsx
src/agenda/reservation-list/reservation.tsx
src/calendar-list/item.tsx
src/calendar/day/basic/index.tsx
src/calendar/day/index.tsx
src/calendar/day/marking/index.tsx
src/calendar/day/period/index.tsx
src/calendar/header/index.tsx
src/expandableCalendar/index.tsx
src/expandableCalendar/week.tsx

All of the internal components' display names were set to `IGNORE`
I assume it's because of private uilib docs. 
Anyway, apparently this affected the call stack of errors, so when there was an error coming from a component with IGNORE display name, it was mention as `IGNORE` and that makes it difficult to investigate issues. 
I also fixed the followings
- There was a type error coming from ExpandableCalender related to the `current` prop. You can see it in the packager when you open the relevant example screen.
I fixed the type of the value we pass to current in ExpandableCalendar
- Also in CalendarList component, I converted the date item we have there back to string before we pass it to the Calendar component

Fix all components display names

---

scripts/release.js

Currently every published version (snapshot or official release) is tagged in git in [here](https://github.com/wix/react-native-calendars/tags)
This will fix it and tag only the official release versions. 
From now own, let's use these release tags for release notes instead of changelog file we have today
I added an example for the latest release
https://github.com/wix/react-native-calendars/releases/tag/1.1272.0

Publish git tags only for official releae versions

---

src/agenda/index.tsx
src/agenda/style.ts

This PR addresses: #1653
Make touchable area of agenda calendar's knob full-width. Confirmed all other calendars(Expandable, Timeline calendar) had the full-width knob by default. So this PR makes the Agenda calendar's knob's behavior aligned to the others.   
Modify Agenda component's style in `Animated.ScrollView`.
<image src="https://user-images.githubusercontent.com/44686790/147300120-95fb982b-6cc3-4369-ac8f-654999238f88.gif" width ="250" height="550">
<image src="https://user-images.githubusercontent.com/44686790/147300132-f826f432-0038-4bbb-8d26-b3da86308fab.gif" width ="250" height="550">

Modify style of agenda calendar's scrollView

---

src/infinite-list/index.tsx
src/timeline-list/index.tsx
src/timeline-list/useTimelinePages.ts

- I renamed HorizontalList to InfiniteList and moved it out of timeline-list folder so it'll be a common component for all other components to use. 
- I made the component more dynamic so it can now accept pageWidth and pageHeight for different types of pages
- I added APIs for onReachEdge and onReachNearEdge since it's a logic that is needed in all cases (instead of each component to calculate that)

Convert HorizontalList to InfiniteList

---

src/index.ts

follow up #1745 and fix the remaining type import error reported in [comment](https://github.com/wix/react-native-calendars/issues/1686#issuecomment-1013966402)

fix type import error

---

example/src/screens/timelineCalendar.tsx
src/timeline/Packer.ts
src/timeline/Timeline.tsx
src/timeline/__tests__/Packer.spec.js

First of all, I refactored the Packer util for Timeline component. 
I mainly changed some function names, fixed typings and add some comments to explain the code (the part of code is very not intuitive) 
Also, I added support for injecting options to the Packer util and specifically in this PR added support to pass a custom right spacing between overlapping events.

Support passing right spacing for overlapping Timeline events

---

src/agenda/index.tsx
src/agenda/reservation-list/index.tsx
src/agenda/reservation-list/reservation.tsx
src/calendar-list/index.tsx
src/calendar-list/item.tsx
src/calendar/day/basic/index.tsx
src/calendar/day/index.tsx
src/calendar/header/index.tsx
src/calendar/index.tsx
src/dateutils.spec.js
src/dateutils.ts
src/expandableCalendar/Context/Presenter.spec.js
src/expandableCalendar/Context/Presenter.ts
src/expandableCalendar/Context/Provider.tsx
src/expandableCalendar/WeekCalendar/index.tsx
src/expandableCalendar/agendaList.tsx
src/expandableCalendar/index.tsx
src/interface.ts
src/services/index.ts

1) Remove comments from old propTypes for cleaner code.
2) Use 'sameMonth' instead of string compare.
3) Use 'getDefaultLocal'.
4) Move 'isPastDate' to dateutils.
5) Optional params in 'sameDate', 'sameMonth' and 'parseDate'.

Remove comments from old PropTypes

---

src/timeline-list/index.tsx
src/timeline/useTimelineOffset.ts

There was an issue with offset sync between timeline pages in timeline list. 
**The bug:** After scrolling to a specific time and then moving to a far off day (using the expandable calendar) the timeline page of the new day didn't keep the scroll offset of the previous day

Fix issue with syncing timelines offset

---

src/index.ts

Just adding the `type` after the `export` makes it compliant for  webpack's `ts-loader`.

types export fix

---

src/expandableCalendar/agendaList.tsx

AgendaList - fix for 'setDisabled' not updating in 'onMomentumScroll' events

AgendaList - fix for 'setDisabled' not updating

---

example/src/screens/timelineCalendarScreen.tsx
src/calendar-list/style.ts
src/calendar/header/index.tsx
src/calendar/header/style.ts
src/dateutils.ts
src/day-state-manager.ts
src/expandableCalendar/Context/Provider.tsx
src/expandableCalendar/Context/calendarProvider.api.json
src/expandableCalendar/Context/index.ts
src/expandableCalendar/WeekCalendar/index.tsx
src/expandableCalendar/WeekCalendar/presenter.ts
src/expandableCalendar/index.tsx
src/expandableCalendar/style.ts
src/expandableCalendar/week.tsx
src/timeline-list/index.tsx
src/timeline-list/useTimelinePages.ts
src/timeline/NowIndicator.tsx
src/timeline/Timeline.tsx
src/timeline/TimelineHours.tsx
src/timeline/__tests__/presenter.spec.js
src/timeline/helpers/presenter.ts
src/timeline/style.ts

Timeline x days view
To see the changes, please uncomment line # 242 in the timelineCalendarScreen (and you can change it to any other number from 1 to 7) 
And sorry about this big PR 🙈 
WOAUILIB-2613

Feat/ timeline x days view

---

src/agenda/index.tsx

When 'selected' prop changes we set the new `selectedDate` to state, but the calendar doesn't scroll to that date and keeps its position on the previous `selectedDate`. This is a fix for that scenario.

Agenda - scroll to new selected date

---

package.json

fs is a core Node.js module - at the moment this is installing https://www.npmjs.com/package/fs which is a security holding package with no content

deps: remove redundant fs

---

src/expandableCalendar/Context/Presenter.spec.js
src/expandableCalendar/Context/Presenter.ts
src/expandableCalendar/Context/Provider.tsx

Move `setDate` and `setDisabled` back to Provider and removing the Presenter's relevant tests

CalendarContextProvider - use with pure functions

---

src/dateutils.ts
src/day-state-manager.ts

dateutils - isDateNotInRange - change parameters type to perform convert inside the tool

dateutils - isDateNotInRange - types

---

src/expandableCalendar/WeekCalendar/index.tsx

Fix the bug when the arrow press doesn't affect the timeline calendar days
The bug was caused because of this PR - https://github.com/wix/react-native-calendars/pull/1941

Fix TimelineCalendars arrow press

---

src/expandableCalendar/index.tsx

ExpandableCalendar - fix week scroll crash by restoring current prop

ExpandableCalendar - fix week scroll crash by restoring current prop

---

example/src/screens/expandableCalendarScreen.tsx
src/calendar-list/index.tsx
src/calendar/index.tsx
src/expandableCalendar/Context/Provider.tsx

ExpandableCalendar - fix double render on load by blocking CalendarList's onVisibleMonthChange from invoking setDate.
Also, move Calendar and CalendarContextProvider to use `useDidUpdate` to avoid logic on load

ExpandableCalendar - fix double render on load

---

src/agenda/index.tsx
src/agenda/reservation-list/index.tsx
src/componentUpdater.ts
src/types.ts

Agenda - extract CalendarList and ReservationList props + ReservationList - extract Reservation props - new methods

Agenda - fix CalendarList props extraction

---

src/calendar-list/index.tsx

CalendarList - fix - update months doesn't apply to the initial month

CalendarList - fix - update months doesn't apply to the initial month

---

.buildkite/pipeline.yml
scripts/release.js

Release script - 1) add a hotfix (patch version) option to the release build process. 2) Fix the release tag generator.

release script - add 'hotfix' option in release build + fix release tag generator

---

README.md
src/agenda/index.tsx

Meant to allow overriding of how the `<Agenda />` component renders the list (use something different than a `FlatList`).

feature: Add support for overriding existing implementation of the agenda's ReservationList

---

src/expandableCalendar/agendaList.tsx

AgendaList - improve loading:
1) fix initial scroll not to perform if the user started to scroll before it was executed. 
2) Change `useEffect` to `useDidUpdate` to avoid second scroll on load (scroll to the current location can be expensive too).

AgendaList - improve loading

---

example/src/screens/expandableCalendarScreen.tsx
src/calendar/index.tsx
src/expandableCalendar/index.tsx

Fix 'headerStyle' prop not applied

ExpandableCalendar - fix passing 'headerStyle' to horizontal header

---

example/src/screens/calendarScreen.tsx

Without these changes instead of adding 1 month, we were adding 2 months

Fix wrong month setting at examples

---

src/calendar/day/period/style.ts

date.day (number) was not vertically centered on a marked period.

fix date.day text not vertically centered

---

example/src/screens/calendarPlaygroundScreen.tsx
src/calendar/day/period/index.tsx
src/calendar/day/period/style.ts

Fix text not align to center in period marking
To test go to CalendarPlaygroundScreen and select 'period' for Marking type.

Period - fix - text alignment

---

src/expandableCalendar/index.tsx

before:
after:
(the issue with seeing the week below wasn't reproduced on android)

fix numberOfDays issues

---

src/componentUpdater.ts

Fix: #2039 
This PR solves the issue of changing the date color in Agenda items via props.

Added fix for Agenda theme prop bug

---

src/calendar-list/index.tsx

Fixes this issue: [#2050](https://github.com/wix/react-native-calendars/issues/2050)

fix(#2050): prevent date overflow when the current date day is 31

---

example/src/screens/expandableCalendarScreen.tsx
src/expandableCalendar/Context/todayButton.tsx

Was set to 0 so when scrolling the AgendaList the button text disappeared.
This should be hotfixed when merged.

TodayButton - fix 'disabledOpacity' prop default value

---

android/build.gradle
package.json

Fix Android build: lock rnn version and add `exclusiveContent` to build.gradle

Fix Android build

---

src/calendar-list/index.tsx
src/calendar-list/item.tsx
src/calendar/index.tsx
src/expandableCalendar/index.tsx
src/types.ts

Calendar - fix double selection - generated from both 'markedDates' and 'state' props.
In controlled components, like Calendar and CalendarList, the selection is marked by the 'markedDates' passed by the user.
In an uncontrolled component, like ExpandableCalender, the selection is made by the 'state' passed by the component.
To fix the double selection I'm passing 'context' to the Calendar component from ExpandableCalendar, thus indicating that this is an uncontrolled component and the selection should be made from the 'state' prop. 
Otherwise, it will disable the selection through the 'state' prop passing **true** to getState() function's 'disableDaySelection' parameter.

Calendar - fix double selection

---

package.json

It looks like this dependency isn't used anymore — this change removes it. I spotted this while looking at our bundle and realized `immutable` doesn't seem to be used.
Thanks for the library!

Remove unused dependency on immutable

---

docsRNC/docs/Agenda.md
docsRNC/docs/AgendaList.md
docsRNC/docs/Calendar.md
docsRNC/docs/CalendarList.md
docsRNC/docs/CalendarProvider.md
docsRNC/docs/ExpandableCalendar.md
docsRNC/docs/Timeline.md
docsRNC/docs/WeekCalendar.md
docsRNC/docusaurus.config.js

Fixing:
- Links to other components where there's more than 1 are broken because of invalid Markdown code, splitting them into their own links
- Links to example screens are broken, replacing with new file names
- Clicking `Edit this page` in the docs takes to a 404 because URL is not specified, setting is to the correct path in docs config

fix broken links in docs

---

src/expandableCalendar/WeekCalendar/index.tsx

WeekCalendar - fix scroll position when 'numberOfDays' prop changes

WeekCalendar - fix scroll position when 'numberOfDays' prop changes

---

package.json

Upgrade is needed b/c this project brings in an old version of `promise` that breaks Sentry's promise swizzle
```
├─┬ @wix/glimpse@0.2.0
│   └── promise@8.3.0
└─┬ @wix/wix-react-native-ui-lib@5.51.6
└─┬ react-native-calendars@1.1295.0
└─┬ recyclerlistview@3.0.5
└─┬ prop-types@15.5.8
└─┬ fbjs@0.8.18
└── promise@7.3.1 /// <--- we want v8
```
After the upgrade:
```
└─┬ recyclerlistview@4.2.0
└─┬ react-native@0.71.8
└── promise@8.3.0
```

upgrade recyclerlistview to v4

---

src/calendar/day/basic/style.ts

When using a custom font, the date number of the selected date in the standard calendar is not vertically centered.
Same thing was already done for the "period" styling in a different PR, see: https://github.com/wix/react-native-calendars/pull/2026

Fix date number not centered vertically

---

example/src/screens/calendarListScreen.tsx
src/calendar-list/index.tsx

The arrow press should stop passing months in the static header when getting to the end of the past/future scroll range.
To test: in the **horizontal CalendarList screen** change the `past/futureScrollRange` prop to 0 or a small number and press the arrows to move btw months - when you get to the edges you can see the months in the header changing but the calendar is off - the months should not change at all. This PR fix this bug.

CalendarList - fix staticHeader moves month out of range

---

src/expandableCalendar/index.tsx

ExpandableCalendar - limit the max open height to the open height (not allowing the user to drag lower)

ExpandableCalendar - limit the max open height

---

src/expandableCalendar/agendaList.tsx
src/expandableCalendar/infiniteAgendaList.tsx
src/infinite-list/index.tsx

This pull request introduces several enhancements to the `infiniteAgendaList` component:
1. **Debouncing of Date Indication Changes:** We've added a new `visibleIndicesChangedDebounce` property. This allows users to control the debounce time for the change date indication on the calendar.
2. **Customizable Footer Rendering:** A new `renderFooter` option has been passed for the `RecyclerListView`. This provides flexibility in how the list's footer is displayed. Particularly, this addition could be beneficial for improving the appearance of loader views.
3. **Improved Scrolling on Android:** By adding `nestedScrollEnabled: true` to the `scrollViewProps`, this will add support for inner scrolling on Android devices.

Enhance infiniteAgendaList

---

src/expandableCalendar/agendaList.tsx
src/expandableCalendar/infiniteAgendaList.tsx
src/infinite-list/index.tsx

This PR addresses the following improvements:
- Eliminates jumping when `onEndReach` is called.
- Manually triggers `onMomentumScrollEnd` in `scrollToSection` (mimics automatic behavior in `sectionList`).
- Avoids unnecessary calls to `scrollToIndex` when already in the correct position.
- Reverts [c4bd90f](https://github.com/wix/react-native-calendars/pull/2286) to fix #2292.

fix(infiniteAgendaList): fixes

---

src/interface.spec.js

parseDate - verify null input is not breaking

parseDate - verify null input is not breaking

---

src/expandableCalendar/infiniteAgendaList.tsx

Since the `AgendaListProps` extends `SectionListProps` we can receive any section list props.
This PR just moves them to the right place inside `InfiniteAgendaList`

feat(infiniteAgendaList): support passing scrollViewProps

---

README.md

Noticed a small typo where the markdown links are included in the code blocks. Thanks in advance for your review!

docs: Removes MD links from code blocks

---

src/types.ts

Added `reservationsBackgroundColor` to `Theme` typings, it was causing a confusion on updating the background colour of the reservations, leaving people without a clue on what to use to be able to change the background colour [convo here ](https://github.com/wix/react-native-calendars/issues/2000)

Added `reservationsBackgroundColor` to Theme typings

---

example/src/screens/calendarScreen.tsx
src/calendar/day/period/index.tsx

Fix the bug that the backgroundColor defined in customContainerStyle will be overwritten

fix: fix custom style on Calendar type: period

---

example/src/mocks/agendaItems.ts
example/src/screens/agendaInfiniteListScreen.tsx
example/src/screens/index.ts
example/src/screens/menuScreen.tsx
example/src/testIDs.ts
src/expandableCalendar/AgendaListsCommon.tsx
src/expandableCalendar/infiniteAgendaList.tsx

In the infinite agenda list, the item height is predefined. We need a way to set multiple item sizes per elements (and not only for title and item)

feat(infiniteAgendaList): add the ability to set item height per item

---

src/expandableCalendar/agendaList.tsx

Added forwardRef to AgendaList (This is needed to support it with the `CollapsingHeader` component). Currently it throws a warning and the `CollapsingHeader` doesn't work well.

Added forwardRef to AgendaList

---

src/commons/constants.ts
src/expandableCalendar/WeekCalendar/index.tsx

with RN 73 the scroll to index method in RTL horizontal Flatlist works as expected which means our previous fix is redundant for those versions, used a check in the calendar itself to avoid sending unnecessary props

week calendar scroll index correction in RN73

---

src/expandableCalendar/agendaList.tsx
src/expandableCalendar/infiniteAgendaList.tsx

Added leading invocation to scrollToSection in AgendaList and InfiniteList AgendaList.
Ticket:
MADS-4420

Remove scroll delay in AgendaList

---

src/expandableCalendar/index.tsx

Added overflow hidden so vertical calendar header won't go outside of the component.

Hide ExpandableCalendar header when going out of container

---

src/commons/constants.ts

When running in a web (react-native-web) env `Platform.constants` doesn't exist. This falls back to false in that case instead of throwing an error.

Fix error with Platform.constants doesn't exists on react-native-web

---

src/expandableCalendar/index.tsx

We can (and should probably) hf this.

Removed hidden for accessible calendar

---

example/src/screens/playgroundScreen.tsx

Fixed function name in playgroundScreen.tsx:
renderExpendableCalendar -> renderExpandableCalendar

Fix typo in example

---

src/expandableCalendar/index.tsx

**Problem Cause:**
When `ExpandableCalendar` was configured with `initialPosition={Positions.OPEN}`, the calendar's total open height `startHeight` was calculated before the actual height of the header section `headerHeight` was determined. This led to headerHeight being treated as `0` or an incorrect value, causing the calendar content to appear clipped or the layout to be misaligned, even though the calendar was in an open state.
**Solution:**
1. Fixed that when the `headerHeight` value changes, the logic that calculates the height when the calendar is open `getOpenHeight` immediately reflects this and recalculates the startHeight correctly.
2.  Also, synchronize the correctly calculated startHeight value to the object that manages native component styles internally `_wrapperStyles` to …

Fix ExpandableCalendar StartHeight calculations
