src/agenda/reservation-list/index.js

I had forgotten the i18n week days in this place.

Show default xdata location in agenda reservation

---

README.md

Fixed some typo erros , all checked on Vs Code.

Typo errors README.md

---

example/package.json
package.json
src/agenda/index.js
src/agenda/reservation-list/index.js
src/calendar-list/index.js
src/calendar/day/basic/index.js
src/calendar/day/interactive/index.js
src/calendar/header/index.js
src/calendar/index.js

see #39
I did not add any `isRequired`, but I think we should

Add propTypes to components

---

src/agenda/index.js
src/agenda/style.js
src/input.js

#55 Allows user to drag the knob in agenda calendar to expand it. Also expands the calendar if user simply presses on the knob.
Uses native driver, so should be performant.

Draggable agenda calendar

---

README.md
src/agenda/index.js

Implementing minDate and maxDate Attributes in Agenda View

Implementing minDate and maxDate Attributes in Agenda View

---

README.md
src/calendar-list/index.js
src/calendar/header/index.js
src/calendar/index.js

Add hideDayNames props. If its `true`, day names arent visible. Now it looks like this:

Add hideDayNames prop

---

src/calendar/index.js

Add missing prop disableMonthChange to Calendar

---

src/calendar/day/basic/index.js
src/calendar/day/interactive/index.js
src/calendar/index.js

Reduce re-rendering of day components

---

README.md

Update README.md - Fix spelling

---

src/calendar-list/item.js

Supports sending `hideDayNames` prop to CalendarList

Add hideDayNames prop to calendarList

---

src/calendar/day/multi-dot/index.js

Fixed bug when multi-dot markers change and the change doesn't re-render the multi-dot day component.

Bug fix for multi-dot markers

---

src/agenda/index.js

update index.js Agenda

---

src/agenda/index.js
src/agenda/reservation-list/reservation.js
src/calendar-list/item.js
src/calendar/day/basic/index.js
src/calendar/day/multi-dot/index.js
src/calendar/day/period/index.js
src/calendar/header/index.js

🐛 Disallow font scaling

---

src/calendar-list/item.js

It was this easy @jarrx, sorry I didn't get to it earlier.
Continuation from https://github.com/wix/react-native-calendars/pull/262

🐛 Fix week numbers for CalendarList

---

src/calendar/header/index.js

add accessibilityTraits='header'
fixes #373

fix: enhance calendar month title accessibility

---

src/calendar/header/index.js

additional change to #374  required for android

fix: enhacement for android accessibility

---

README.md
src/calendar/day/basic/index.js
src/calendar/day/multi-dot/index.js
src/calendar/day/period/index.js
src/calendar/index.js

Implementation of function that executes on day component long press

Day long press

---

src/calendar-list/index.js

This PR makes calendarHeight dynamic.
calendarHeight is passed as props in the CalendarList. If no calendarHeight props is passed, it takes the default as it was => 360.

Dynamic calendarHeight

---

src/calendar/index.js
src/calendar/style.js

Now you can style the weeks wrapper. In my case I had to separate it from header (with margin).

Add a wrapper for weeks to be able to style it

---

src/calendar-list/index.js
src/calendar-list/item.js
src/calendar/header/index.js

* Change conditions to more efficient defaultProps
* Giving more flexibility to the components (Ability to change components through props)

Changing conditions to defaultProps

---

src/calendar-list/item.js

Thanks to the issue #505 I implemented and tested the code.

Add arrows to CalendarList #505

---

README.md

fix typo about README

---

example/src/screens/expandableCalendar.js
src/calendar-list/index.js
src/calendar-list/item.js
src/calendar-list/style.js
src/calendar/header/index.js
src/calendar/index.js
src/expandableCalendar/index.js

CalendarList - adding 'staticHeader' option.
Calendar - exposing 'headerStyle' prop to pass CalendarHeader.

CalendarList - Static header

---

src/calendar-list/index.js

Add onEndReached and OnEndReachedThreshold to Flatlist props in CalendarList

Add onEndReached and OnEndReachedThreshold to Flatlist props

---

src/agenda/index.js
src/agenda/reservation-list/index.js

Added the ability to catch scroll events of the agenda flatlist
Tested on iOS and Android.

Adding scroll events to the agenda list

---

src/calendar-list/item.js

Implemented the proposed solution in  #1051 and it solves the problem. Implementation is similar to momentjs.

Fix previous months bug

---

example/src/screens/expandableCalendar.js
example/src/screens/menu.js
src/agenda/reservation-list/index.js
src/agenda/reservation-list/reservation.js
src/expandableCalendar/agendaList.js
src/expandableCalendar/index.js

Resolves #962

---

example/src/screens/calendars.js
src/calendar/index.js

Resolves #961

---

src/agenda/index.js

Resolves #1132
Thanks to @dansokol

Resolves #1132

---

CHANGELOG.md
README.md
example/src/app.js
example/src/screens/calendarsList.js
src/calendar-list/item.js
src/calendar/header/index.js
src/calendar/header/style.js
src/calendar/index.js

Inspired by https://github.com/wix/react-native-calendars/pull/1177, fixing some issues with this PR and update the example.
Thanks to @jacm80 for this wonderful feature.

Custom Header In Calendar

---

ios/Podfile.lock

I have added demo for timeline calendar feature, as requested by @chenei

Demo for Timeline Calendar

---

src/calendar/dot/index.js

fixes https://github.com/wix/react-native-calendars/issues/1226

Do not override marked style with today style

---

.eslintrc.js
.prettierignore
.prettierrc.js
.prettierrc.json
package.json

Basic Prettier setup. I didn't reformat the files because we would get too many merge conflicts in PRs.

Setup Prettier

---

example/src/screens/calendars.js
src/calendar-list/item.js
src/calendar/index.js

Allows you to completely override the header.
Similar to #546 but it fixes the problems.

Implement a custom header prop

---

src/expandableCalendar/agendaList.js

Allows creating custom header at the top of each section in AgendaList

allow custom section header in agendalist

---

example/src/app.js
example/src/wdyr.js
ios/Podfile.lock
package.json

Adding 'why-did-you-render' lib to track rendering in development

setting up 'why-did-you-render'

---

src/calendar/day/multi-period/index.js
src/calendar/day/multi-period/style.js

Fix day text align on multi-period (modified)

---

CHANGELOG.md
src/agenda/reservation-list/index.js
src/agenda/reservation-list/reservation.js
src/expandableCalendar/agendaList.js

Adding 'dayFormatter' and 'markToday' props; 
editing reservations commets

AgendaList - Adding 'dayFormatter'

---

CHANGELOG.md
detox.config.js
e2e/init.js
example/src/screens/calendars.js
package.json

Detox upgrading to 18.6.2

---

CHANGELOG.md
src/expandableCalendar/agendaList.js

AgendaList - 'blockDateUpdate' to block updates to the CalendarContextProvider when list scrolls

AgendaList - block date updates

---

example/src/screens/calendars.js
example/src/screens/timelineCalendar.js
package.json
src/expandableCalendar/agendaList.js
src/momentResolver.js
src/timeline/Packer.js
src/timeline/Timeline.js

Moment.js is a legacy project in maintenance mode now and this repo use xdate library for dates.

moment js as an optional dependency

---

CHANGELOG.md
example/src/screens/expandableCalendar.js
src/calendar-list/index.js

CalendarList - Adding `animateScroll` prop to allow animating auto-scroll (i.e. on arrow press).

CalendarList - Adding `animateScroll` prop

---

CHANGELOG.md
example/src/screens/calendars.js
example/src/screens/calendarsList.js
src/agenda/index.js
src/agenda/style.js
src/expandableCalendar/calendarProvider.js
src/expandableCalendar/index.js
src/expandableCalendar/style.js
src/expandableCalendar/weekCalendar.js

Run 'npm run lint' to see rest of the warnings

fix inline style

---

CHANGELOG.md
example/src/screens/expandableCalendar.js

ExpandableCalendar demo - Moving 'renderItem' to use memoized functional component.

ExpandableCalendar demo - performance

---

scripts/release.js

Support releasing a snapshot version for calendar in order to check versions during development

Release snapshots

---

src/expandableCalendar/index.js

fix the bug from the timeline screen (today button)

Fix/ set month only if exists

---

example/src/screens/menu.js
src/calendar/day/marking/index.tsx

Fix bug in marking and update weekCalendar screen name

Fix bug in marking + update weekCalendar screen name

---

example/src/screens/calendars.tsx
src/calendar/day/basic/index.tsx
src/calendar/day/basic/style.ts
src/calendar/day/dot/index.tsx
src/calendar/day/dot/style.ts
src/calendar/day/marking/index.tsx
src/calendar/day/period/index.tsx
src/calendar/day/period/style.ts
src/commons/types.ts
src/style.ts
src/types.ts

Add support for inactive days (in addition to disabled days)

Feat/ support inactive state for day

---

src/calendar/index.tsx

Add allowSelectionOutOfRange prop to Calendar component to support a selection of past date in range picker.

Add allowSelectionOutOfRange prop to Calendar

---

src/expandableCalendar/WeekCalendar/presenter.spec.js
src/expandableCalendar/WeekCalendar/presenter.ts

Fix weekCalendar swiping bug
WOAUILIB-2117

Fix/ weekCalendar swiping bug

---

example/src/screens/expandableCalendar.tsx
src/expandableCalendar/agendaList.tsx

Update the agenda position after pressing on any date (and not only while pressing date with a content in the agenda)
WOAUILIB-2119

Fix/ AgendaList dayPress

---

src/calendar/style.ts
src/style.ts
src/types.ts

Have added weekVerticalMargin in theme to control margin between week rows.

new theme prop, weekVerticalMargin, handle week row height

---

src/expandableCalendar/index.tsx

Only hide extra days on ExpandableCalendar when open

---

src/index.ts
src/services/index.ts

Apparently the packager didn't like how I exported the CalendarUtils, I fixed it

Fix CalendarUtils export

---

example/src/screens/calendars.tsx
src/calendar/header/index.tsx
src/calendar/index.tsx

CalendarHeader - add 'customHeaderTitle' prop for passing custom element

CalendarHeader - 'customHeaderTitle' prop

---

src/timeline/EventBlock.tsx
src/timeline/Packer.ts
src/timeline/Timeline.tsx
src/timeline/TimelineHours.tsx

In order to prepare the grounds for the new features for Timeline component, I first wanted to refactor the component 
In this PR I break the main Timeline component into small components - EventBlock and TimelineHours

Refactor Timeline component - part1

---

example/src/screens/timelineCalendar.tsx
src/timeline/Timeline.tsx

In order to prepare the grounds for the new features for Timeline component, I first wanted to refactor the component
In this PR I covert the Timeline component to a function component 
This PR depends on https://github.com/wix/react-native-calendars/pull/1722

Refactor Timeline component - part2

---

src/timeline/EventBlock.tsx
src/timeline/Packer.ts
src/timeline/Timeline.tsx
src/timeline/TimelineHours.tsx
src/timeline/__tests__/Packer.spec.js

Adding unit tests to Timeline Packer util before we're adding new features 
This should be reviewed only after this PR was merged - https://github.com/wix/react-native-calendars/pull/1723

Add unit tests for the Packer util

---

example/src/screens/agenda.tsx
src/agenda/index.tsx
src/agenda/reservation-list/index.tsx
src/agenda/reservation-list/reservation.tsx
src/index.ts
src/types.ts
tsconfig.json

Agenda - fix types.
I added the Agenda demo screen to the type check and started fixing the types on all its related components.
Please double-check that I don't have any breaking changes!!

Agenda - types fix

---

example/src/screens/timelineCalendar.tsx
src/timeline/Timeline.tsx
src/timeline/TimelineHours.tsx
src/timeline/__tests__/presenter.spec.js
src/timeline/helpers/presenter.ts
tsconfig.json

- Support timeline background (long) press for creating new events - currently this is a very simple behavior till we have the final UX
- Enable TS in the Timeline example screen 
- Added usage example
- Move logic to a presenter file and add tests

Support timeline background press for creating new events

---

example/src/screens/timelineCalendar.tsx
src/timeline/NowIndicator.tsx
src/timeline/Timeline.tsx
src/timeline/TimelineHours.tsx
src/timeline/style.ts
src/types.ts

- Support showing Now Indicator for the Timeline component. 
- Improve UI for timeline grid

Support Timeline now indicator and fix UI for timeline grid

---

example/src/screens/timelineCalendar.tsx
src/timeline/Timeline.tsx
src/timeline/TimelineHours.tsx
src/timeline/__tests__/presenter.spec.js
src/timeline/helpers/presenter.ts

This for identifying the Timeline instance, especially later on when we'll support 3 days view

Support passing date to Timeline

---

scripts/release.js

Release script - fix git tagging command

Release script - fix git tagging command

---

src/expandableCalendar/Context/Presenter.ts
src/expandableCalendar/Context/Provider.tsx
src/expandableCalendar/Context/index.ts
src/types.ts

Add types for the Expandable Calendar Context and fix some issues I found

Fix ExpandableCalendar Context type

---

example/src/screens/calendars.tsx
src/expandableCalendar/index.tsx
src/expandableCalendar/style.ts

ExpandableCalendar - fix Android bottom padding in the open position.
Calendars demo screen - fix crash

ExpandableCalendar - fix Android bottom padding.

---

src/index.ts
src/timeline-list/index.tsx

Support passing a renderItem prop to TimelineList to render a custom item

Support custom renderItem in TimelineList component

---

src/expandableCalendar/index.tsx

ExpandableCalendar - fix calendar height not updated after day press

ExpandableCalendar - fix calendar height not updated after day press

---

example/src/screens/agenda.tsx
src/agenda/reservation-list/index.tsx

Agenda - fix `keyExtractor` for reservation list and allow passing a custom one

Agenda - fix keyExtractor for reservation list

---

example/src/screens/menu.tsx
src/calendar-list/index.tsx
src/calendar/day/basic/style.ts
src/commons/constants.ts
src/expandableCalendar/WeekCalendar/index.tsx
src/expandableCalendar/WeekCalendar/presenter.ts
src/expandableCalendar/agendaList.tsx
src/expandableCalendar/commons.ts
src/expandableCalendar/index.tsx
src/expandableCalendar/style.ts
src/timeline/TimelineHours.tsx
src/timeline/style.ts

Moving all constants to a common file in src directory and use them on all components.
Adding RTL option in the menu screen.

Constants cleanup

---

src/calendar/day/basic/index.tsx
src/calendar/header/index.tsx

Adding missing dependencies to callbacks in Header and BasicDay components

Fix - Adding missing dependencies to callbacks

---

src/agenda/index.tsx

Agenda - fix for crash when 'selected' prop is undefined.
solved issue #1802

Agenda - fix for 'selected' as undefined

---

README.md

This PR adds a banner supporting our Ukrainian colleagues from Kyiv, Dnipro, and Lviv offices.
Detox, RN navigation, and RN UI library have already added such banners.

Add StandWithUkraine banner

---

src/calendar/day/index.tsx

Day - fix date prop's return type for custom 'dayComponent' to avoid a breaking change

Day - fix date prop's return type for 'dayComponent'

---

src/agenda/index.tsx

Agenda - BUG fix - onDayPress triggering additional day reset
Soloves issue #1837

Agenda - BUG fix - onDayPress triggering additional day reset

---

src/calendar/index.tsx
src/expandableCalendar/index.tsx

Calendar - fir swipe direction for RTL.
ExpandableCalendar - fix month jumps back when scrolling on an open position

ExpandableCalendar - fix scrolling open calendar

---

docsRNC/docs/CalendarList.md

**Calendar, FlatList** should be two separate links

Update CalendarList.md 

---

src/expandableCalendar/agendaList.tsx

AgendaList - invoke onViewableItemsChanged callback
solves issue #1883

AgendaList - invoke onViewableItemsChanged callback

---

example/src/screens/expandableCalendarScreen.tsx
src/expandableCalendar/style.ts
src/style.ts

App style - Add support for ExpandableCalendar's knob color

App style - Add support for ExpandableCalendar's knob color

---

src/calendar/index.tsx
src/expandableCalendar/index.tsx

Day - fix performance - all days are being rendered when selecting a new day

Day - performance fix

---

src/timeline/Timeline.tsx
src/timeline/style.ts
src/timeline/timeline.api.json
src/types.ts

Fix Timeline styles - removing unused styles, get background from app style, adding verticalLine to theme, ordering style overrides

Fix Timeline styles

---

example/src/screens/calendarScreen.tsx

Calendar example - customHeader prop - usage.
How to use customHeader props to read and change current month.

Calendar example - customHeader prop - usage

---

android/app/build.gradle
android/app/proguard-rules.pro
ios/CalendarsExample.xcodeproj/project.pbxproj
ios/Podfile
ios/Podfile.lock
package.json

Enable Hermes for demo app
Add react-recipets in dev dependencies

enable Hermes

---

src/calendar/day/index.tsx
src/calendar/index.tsx
src/componentUpdater.ts
src/interface.ts

Calendar & Day - replacing 'extractComponentProps' with less generic method, and reimplementing toMarkingString function

Calendar & Day - Performance improvements

---

src/expandableCalendar/week.tsx

Fix callback passed to onLongPress prop

Week - pass `onDayLongPress`

---

src/expandableCalendar/agendaList.tsx

AgendaList - debounce `scrollToSection`; remove propTypes

AgendaList - debounce `scrollToSection`

---

src/expandableCalendar/index.tsx

Also: reorganize code, remove propTypes, and wrap const with useMemo and useCallback

ExpandableCalendar - close calendar with knob press

---

example/src/screens/menuScreen.tsx
example/src/screens/playgroundScreen.tsx
src/Profiler.tsx
src/index.ts

Adding Profiler to text component's performance on mount and update

Adding a profiler and adding playgroundscreen for examples

---

src/expandableCalendar/Context/Provider.tsx

AgendaList - fix Today button not active when end scroll

AgendaList - fix Today button not active when end scroll

---

src/dateutils.spec.js
src/dateutils.ts
src/expandableCalendar/index.tsx

dateutils month

---

example/src/screens/calendarPlaygroundScreen.tsx
example/src/screens/index.ts
example/src/screens/menuScreen.tsx

Adding Calendar playground screen to allow playing with calendar's props dynamically

Calendar playground screen

---

src/dateutils.ts
src/expandableCalendar/WeekCalendar/presenter.ts
src/timeline/helpers/presenter.ts

dateutils - 'generateDay' function - add XDate as a type to reduce unnecessary parsings

dateutils - generateDay - add XDate as a type

---

src/dateutils.ts
src/expandableCalendar/Context/Presenter.ts
src/expandableCalendar/agendaList.tsx
src/timeline-list/index.tsx

dateutils - isToday function - add string type to reduce unnecessary converts

dateutils - isToday function - add string as type 

---

src/calendar/day/basic/index.tsx
src/calendar/day/index.tsx
src/calendar/day/period/index.tsx
src/interface.ts

dateutil - xdateToData function - add string type and move convert inside

dateutil - xdateToData function - types

---

src/agenda/index.tsx
src/calendar/index.tsx
src/dateutils.ts
src/expandableCalendar/agendaList.tsx
src/expandableCalendar/week.tsx

dateutils - parseDate - reduce usage

dateutils - parseDate - reduce usage

---

src/expandableCalendar/index.tsx

ExpandableCalendar - fix - when calendar closed arrow press doesn't set the first day of the week (sets the dame day, e.g. Wednesday)

ExpandableCalendar - fix - day set when arrow press while closed

---

src/expandableCalendar/WeekCalendar/index.tsx
src/expandableCalendar/index.tsx

ExpandableCalendar - selection made from Day.state prop instead of `markedDates`

ExpandableCalendar - day selection

---

src/momentResolver.ts

Make moment actually optional

---

src/calendar/header/index.tsx

Fixed the issue in calendar header individual day header style (dayTextAtIndex${index}) does not applied

fix individual day header style

---

example/src/screens/calendarListScreen.tsx
example/src/screens/calendarPlaygroundScreen.tsx
example/src/screens/calendarScreen.tsx
src/day-state-manager.ts
src/expandableCalendar/WeekCalendar/index.tsx

day-state-manager - fix 'disabled' state overriding 'selected' state.
demo screens - fix markedDates's selected entry from being overridden by other marked dates.

Fix day selection

---

src/calendar-list/index.tsx

CalendarList - check date passed to xdateToData()

CalendarList - fix convert undefined error

---

src/timeline/Timeline.tsx
src/timeline/TimelineHours.tsx

Added missing keys for Timeline and TimelineHours components

Fixed unique key warnings for timeline

---

example/src/screens/expandableCalendarScreen.tsx

This is a current issue that needs patching.
Thanks!

Prevents from crashing

---

.buildkite/pipeline.yml

speed up CI builds with better machines

move to bare metal machines

---

package.json

- https://snyk.io/vuln/npm:moment@2.29.1

fix: moment 2.29.1 vulnerabilities

---

src/expandableCalendar/__test__/index.spec.ts
src/expandableCalendar/index.tsx

ExpandableCalendar - fix calendar position when 'numberOfDays' is defined and greater than 1

ExpandableCalendar - fix calendar position with 'numberOfDays'

---

src/expandableCalendar/index.tsx

ExpandableCalendar - fix transition bwt positions (open/close)
The fix is on the pan responder, the rest is minor organizing...

ExpandableCalendar - fix transition bwt positions (open/close)

---

src/interface.ts

toMarkingFormat - Cannot convert undefined value to object

toMarkingFormat - Cannot convert undefined value to object

---

src/dateutils.spec.js
src/dateutils.ts

Secure isLTE and isGTE functions
Fix error: Cannot read property 'getTime' of undefined

Secure isLTE and isGTE functions

---

src/interface.ts

Revert: toMarkingFormat - Cannot convert undefined value to object (#2409)

Revert: toMarkingFormat - Cannot convert undefined value to object (#2409)

---

README.md

typofix: README.md

---

src/expandableCalendar/index.tsx

solves https://github.com/wix/react-native-calendars/issues/2280

fix(ExpandableCalender): laggy animation

---

example/src/mocks/agendaItems.ts

Fixed variable name fastDate -> pastDate

Fix example typo

---

src/expandableCalendar/index.tsx

Added leave animation to animated header

---

example/src/screens/expandableCalendarScreen.tsx
src/expandableCalendar/index.tsx

Removed `bouneToPosition` disabling with disablePan. Disabled header closing on day press with disablePan.

ExpandableCalendar - TogglePosition with disablePan

---

src/calendar-list/index.tsx
src/calendar/header/index.tsx

Added testID passing to the CalendarList.renderHeader function

CalendarList - Passing testID to renderHeader function
